import { useEffect, useState, type FormEvent } from 'react';
import { Info, Plug, Plus, RefreshCw } from 'lucide-react';
import {
  createSyncRun,
  finishSyncRun,
  listIntegrations,
  listSyncRuns,
  saveIntegration,
  type IntegrationRecord,
  type IntegrationType,
  type SyncRunRecord,
} from '../data/supabaseOperations';

const typeLabel: Record<IntegrationType, string> = {
  control_acceso: 'Control de acceso', erp: 'ERP', previred: 'Previred', webhook: 'Webhook',
};

export default function IntegrationsPanel({ projectKey, showToast }: { projectKey: string; showToast: (message: string, type?: 'success'|'error'|'warning') => void }) {
  const [items,setItems]=useState<IntegrationRecord[]>([]); const [runs,setRuns]=useState<Record<string,SyncRunRecord[]>>({}); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({type:'control_acceso' as IntegrationType,provider:'',endpointUrl:'',enabled:false});
  const load=async()=>{try{const next=await listIntegrations(projectKey);setItems(next);const pairs=await Promise.all(next.map(async item=>[item.id,await listSyncRuns(item.id)] as const));setRuns(Object.fromEntries(pairs));}catch(error){showToast(error instanceof Error?error.message:'No fue posible cargar integraciones.','error');}};
  useEffect(()=>{void load();},[projectKey]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.provider.trim()||saving)return;setSaving(true);try{await saveIntegration(projectKey,{type:form.type,provider:form.provider,endpointUrl:form.endpointUrl||undefined,enabled:form.enabled});setForm({type:'control_acceso',provider:'',endpointUrl:'',enabled:false});await load();showToast('Configuración de integración guardada.');}catch(error){showToast(error instanceof Error?error.message:'No fue posible guardar la integración.','error');}finally{setSaving(false);}};
  const toggle=async(item:IntegrationRecord)=>{try{await saveIntegration(projectKey,{id:item.id,type:item.integration_type,provider:item.provider,endpointUrl:item.endpoint_url,enabled:!item.enabled,settings:item.settings});await load();showToast(!item.enabled?'Configuración habilitada.':'Configuración deshabilitada.','warning');}catch(error){showToast(error instanceof Error?error.message:'No fue posible actualizar la integración.','error');}};
  const registerRun=async(item:IntegrationRecord)=>{try{await createSyncRun(item.id,'bidireccional');await load();showToast('Ejecución registrada. Debe cerrarse cuando el conector externo entregue su resultado.');}catch(error){showToast(error instanceof Error?error.message:'No fue posible registrar la ejecución.','error');}};
  const closeRun=async(item:IntegrationRecord,run:SyncRunRecord,status:'exitoso'|'fallido')=>{const raw=window.prompt('Registros procesados:',String(run.records_processed||0));if(raw===null)return;const error=status==='fallido'?window.prompt('Detalle del error:')||'Sin detalle':undefined;try{await finishSyncRun(run.id,item.id,status,Number(raw)||0,error);await load();showToast(status==='exitoso'?'Ejecución registrada como exitosa.':'Ejecución registrada como fallida.','warning');}catch(e){showToast(e instanceof Error?e.message:'No fue posible cerrar la ejecución.','error');}};
  return <section className="border rounded-xl p-4 mt-5">
    <div className="flex justify-between items-start gap-3"><div className="flex gap-2"><Plug/><div><h3 className="font-semibold text-navy">Preparación de integraciones</h3><p className="text-sm text-gray-500">Registra proveedores, endpoints e historial operacional para conectar sistemas externos de forma auditable.</p></div></div><button type="button" onClick={()=>void load()} aria-label="Actualizar integraciones"><RefreshCw/></button></div>
    <div className="mt-4 flex gap-2 rounded-lg border border-blue-100 bg-blue-50 p-3 text-xs leading-relaxed text-blue-800"><Info size={16} className="shrink-0 mt-0.5"/><span><strong>Estado actual:</strong> esta pantalla prepara y audita integraciones, pero no ejecuta por sí sola conexiones automáticas con Previred, ERP o controles de acceso. Cada conector debe habilitarse técnicamente con el proveedor correspondiente antes de considerarlo operativo.</span></div>
    <form onSubmit={submit} className="grid grid-cols-1 sm:grid-cols-4 gap-2 mt-4"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as IntegrationType})} className="form-input p-2 border rounded"><option value="control_acceso">Control de acceso</option><option value="erp">ERP</option><option value="previred">Previred</option><option value="webhook">Webhook</option></select><input required value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} className="form-input p-2 border rounded" placeholder="Proveedor"/><input type="url" value={form.endpointUrl} onChange={e=>setForm({...form,endpointUrl:e.target.value})} className="form-input p-2 border rounded" placeholder="Endpoint (opcional)"/><label className="text-sm inline-flex items-center gap-2 border rounded px-3"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Configuración activa</label><button className="btn btn-primary sm:col-span-4" disabled={saving}><Plus/>Agregar configuración</button></form>
    <div className="space-y-3 mt-4">{items.map(item=><div key={item.id} className="border rounded-xl p-3"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><strong>{typeLabel[item.integration_type]} · {item.provider}</strong><small className="block text-gray-500">{item.endpoint_url||'Sin endpoint'} · {item.enabled?'Configuración activa':'Configuración inactiva'}{item.last_sync_status?` · última ejecución: ${item.last_sync_status}`:''}</small></div><div className="flex gap-2"><button type="button" onClick={()=>void toggle(item)}>{item.enabled?'Desactivar':'Activar'}</button><button type="button" onClick={()=>void registerRun(item)}>Registrar ejecución</button></div></div><div className="mt-3 space-y-2">{(runs[item.id]||[]).slice(0,5).map(run=><div key={run.id} className="text-sm border rounded-lg p-2 flex flex-col sm:flex-row justify-between gap-2"><span>{new Date(run.started_at).toLocaleString('es-CL')} · {run.direction} · {run.status} · {run.records_processed} registros{run.error_message?` · ${run.error_message}`:''}</span>{['pendiente','ejecutando'].includes(run.status)&&<div className="flex gap-2"><button type="button" onClick={()=>void closeRun(item,run,'exitoso')}>Cerrar exitosa</button><button type="button" onClick={()=>void closeRun(item,run,'fallido')}>Cerrar fallida</button></div>}</div>)}{(runs[item.id]||[]).length===0&&<p className="text-sm text-gray-500">Sin ejecuciones registradas.</p>}</div></div>)}{items.length===0&&<p className="text-sm text-gray-500">No hay configuraciones de integración registradas.</p>}</div>
  </section>;
}
