import { useEffect, useState, type FormEvent } from 'react';
import { Banknote, ClipboardCheck, Headphones, Plus, RefreshCw } from 'lucide-react';
import type { Contratista, Proyecto } from '../types';
import { createEvaluation, createPayment, createTicket, loadOperations, updatePaymentStatus, updateTicketStatus, type EvaluationRecord, type PaymentRecord, type TicketRecord } from '../data/supabaseOperations';

export default function OperationsCenter({project,contractors,showToast}:{project:Proyecto;contractors:Contratista[];showToast:(message:string,type?:'success'|'error'|'warning')=>void}){
 const [data,setData]=useState<{evaluations:EvaluationRecord[];payments:PaymentRecord[];tickets:TicketRecord[]}>({evaluations:[],payments:[],tickets:[]});const [loading,setLoading]=useState(true);const [mode,setMode]=useState<'evaluacion'|'pago'|'ticket'>('evaluacion');
 const [contractor,setContractor]=useState(contractors[0]?.id||'');const [start,setStart]=useState(new Date().toISOString().slice(0,8)+'01');const [end,setEnd]=useState(new Date().toISOString().slice(0,10));const [subject,setSubject]=useState('');const [description,setDescription]=useState('');const [amount,setAmount]=useState('');const [scores,setScores]=useState({safety:80,quality:80,labor:80,compliance:80});
 const load=async()=>{setLoading(true);try{setData(await loadOperations(project.id));}catch(e){console.error(e);showToast('No fue posible cargar la operación avanzada.','error');}finally{setLoading(false);}};useEffect(()=>{void load();},[project.id]);
 const submit=async(e:FormEvent)=>{e.preventDefault();try{if(mode==='evaluacion')await createEvaluation(project.id,contractor,{start,end,...scores,observations:description});else if(mode==='pago')await createPayment(project.id,contractor,{start,end,amount:amount?Number(amount):undefined,status:'observado',reason:description});else await createTicket(project.id,contractor||undefined,{subject,description,priority:'normal',category:'operacion'});setSubject('');setDescription('');await load();showToast(mode==='evaluacion'?'Evaluación publicada.':mode==='pago'?'Estado de pago creado.':'Ticket creado.');}catch(error){showToast(error instanceof Error?error.message:'No fue posible guardar.','error');}};
 const changePayment=async(id:string,status:'retenido'|'liberado'|'pagado')=>{const reason=status==='retenido'?window.prompt('Motivo de la retención:')||'':undefined;if(status==='retenido'&&!reason)return;try{await updatePaymentStatus(id,status,reason);await load();showToast(`Estado de pago ${status}.`);}catch(error){showToast(error instanceof Error?error.message:'No fue posible actualizar el pago.','error');}};
 const changeTicket=async(id:string,status:'en_progreso'|'resuelto'|'cerrado')=>{const resolution=status==='resuelto'||status==='cerrado'?window.prompt('Resolución aplicada:')||'':undefined;if((status==='resuelto'||status==='cerrado')&&!resolution)return;try{await updateTicketStatus(id,status,resolution);await load();showToast(`Ticket ${status.replace('_',' ')}.`);}catch(error){showToast(error instanceof Error?error.message:'No fue posible actualizar el ticket.','error');}};
 return <article className="mandante-proyectos-section-card mandante-proyectos-panel"><div className="mandante-proyectos-section-head"><div><h2>Operación avanzada</h2><p>Evaluación, riesgo, estados de pago y soporte vinculados al proyecto.</p></div><button type="button" onClick={()=>void load()}><RefreshCw/>Actualizar</button></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 my-4"><button type="button" onClick={()=>setMode('evaluacion')} className="rounded-lg border p-4 text-left"><ClipboardCheck/><strong className="block">Evaluaciones</strong><span>{data.evaluations.length} registradas</span></button><button type="button" onClick={()=>setMode('pago')} className="rounded-lg border p-4 text-left"><Banknote/><strong className="block">Estados de pago</strong><span>{data.payments.length} períodos</span></button><button type="button" onClick={()=>setMode('ticket')} className="rounded-lg border p-4 text-left"><Headphones/><strong className="block">Soporte</strong><span>{data.tickets.filter(x=>!['resuelto','cerrado'].includes(x.status)).length} abiertos</span></button></div>
 <form onSubmit={submit} className="border rounded-xl p-4 grid grid-cols-1 sm:grid-cols-2 gap-3"><h3 className="sm:col-span-2 font-semibold text-navy">{mode==='evaluacion'?'Nueva evaluación':mode==='pago'?'Nuevo estado de pago':'Nuevo ticket'}</h3><label className="text-sm">Contratista<select required={mode!=='ticket'} value={contractor} onChange={e=>setContractor(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"><option value="">Proyecto general</option>{contractors.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label>{mode!=='ticket'&&<><label className="text-sm">Inicio<input type="date" required value={start} onChange={e=>setStart(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"/></label><label className="text-sm">Término<input type="date" required value={end} onChange={e=>setEnd(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"/></label></>}{mode==='evaluacion'&&<div className="sm:col-span-2 grid grid-cols-2 sm:grid-cols-4 gap-2">{Object.entries(scores).map(([key,value])=><label className="text-sm" key={key}>{key==='safety'?'Seguridad':key==='quality'?'Calidad':key==='labor'?'Laboral':'Cumplimiento'}<input type="number" min="0" max="100" value={value} onChange={e=>setScores({...scores,[key]:Number(e.target.value)})} className="form-input w-full mt-1 p-2 border rounded"/></label>)}</div>}{mode==='pago'&&<label className="text-sm">Monto CLP<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"/></label>}{mode==='ticket'&&<label className="sm:col-span-2 text-sm">Asunto<input required value={subject} onChange={e=>setSubject(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"/></label>}<label className="sm:col-span-2 text-sm">{mode==='ticket'?'Descripción':'Observaciones'}<textarea required={mode==='ticket'} value={description} onChange={e=>setDescription(e.target.value)} className="form-input w-full mt-1 p-2 border rounded"/></label><button className="btn btn-primary sm:col-span-2" type="submit"><Plus/>Guardar</button></form>
 <div className="mt-5 mandante-proyectos-table-wrap"><table><thead><tr><th>Tipo</th><th>Período/asunto</th><th>Resultado</th><th>Estado y acciones</th></tr></thead><tbody>{mode==='evaluacion'&&data.evaluations.map(x=><tr key={x.id}><td>Evaluación</td><td>{x.period_start} — {x.period_end}</td><td>{x.total_score}% · Riesgo {x.risk_level}</td><td>{x.status}</td></tr>)}{mode==='pago'&&data.payments.map(x=><tr key={x.id}><td>Pago</td><td>{x.period_start} — {x.period_end}</td><td>{x.amount?`${Number(x.amount).toLocaleString('es-CL')} ${x.currency}`:'Sin monto'}{x.block_reason&&<small className="block text-red-700">{x.block_reason}</small>}</td><td><strong className="block capitalize">{x.status}</strong><div className="flex flex-wrap gap-2 mt-1"><button type="button" onClick={()=>void changePayment(x.id,'retenido')}>Retener</button><button type="button" onClick={()=>void changePayment(x.id,'liberado')}>Liberar</button><button type="button" onClick={()=>void changePayment(x.id,'pagado')}>Pagado</button></div></td></tr>)}{mode==='ticket'&&data.tickets.map(x=><tr key={x.id}><td>{x.category}</td><td>{x.subject}<small className="block text-gray-500">{x.resolution||x.description}</small></td><td>{x.priority}</td><td><strong className="block capitalize">{x.status.replace('_',' ')}</strong><div className="flex flex-wrap gap-2 mt-1"><button type="button" onClick={()=>void changeTicket(x.id,'en_progreso')}>Tomar</button><button type="button" onClick={()=>void changeTicket(x.id,'resuelto')}>Resolver</button><button type="button" onClick={()=>void changeTicket(x.id,'cerrado')}>Cerrar</button></div></td></tr>)}</tbody></table></div>{loading&&<p className="p-4 text-sm text-gray-500">Cargando operación…</p>}</article>;
}
