drop policy if exists evaluations_manage on public.contractor_evaluations;
create policy evaluations_insert on public.contractor_evaluations for insert to authenticated with check ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));
create policy evaluations_update on public.contractor_evaluations for update to authenticated using ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id)))) with check ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));
create policy evaluations_delete on public.contractor_evaluations for delete to authenticated using ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));

drop policy if exists payments_manage on public.payment_cases;
create policy payments_insert on public.payment_cases for insert to authenticated with check ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));
create policy payments_update on public.payment_cases for update to authenticated using ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id)))) with check ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));
create policy payments_delete on public.payment_cases for delete to authenticated using ((select private.is_acredita_staff()) or exists(select 1 from public.accreditations a where a.id=accreditation_id and (select private.can_manage_project(a.project_id))));

drop policy if exists credentials_manage on public.access_credentials;
create policy credentials_insert on public.access_credentials for insert to authenticated with check ((select private.is_acredita_staff()) or (select private.can_manage_project(project_id)));
create policy credentials_update on public.access_credentials for update to authenticated using ((select private.is_acredita_staff()) or (select private.can_manage_project(project_id))) with check ((select private.is_acredita_staff()) or (select private.can_manage_project(project_id)));
create policy credentials_delete on public.access_credentials for delete to authenticated using ((select private.is_acredita_staff()) or (select private.can_manage_project(project_id)));
